In [2]:
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
customers = pd.read_csv("../dags/data/raw/df_Customers.csv")
print(customers.head())
print(customers.info())

    customer_id  customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                     58125     varzea paulista             SP
1  PxA7fv9spyhx                      3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                      4119             jandira             SP
3  EOEsCQ6QlpIg                     18212          uberlandia             MG
4  mVz5LO2Vd6cL                     88868            ilhabela             SP
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  object
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  object
 3   customer_state            89316 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.7+ MB
None

In [4]:
order_items = pd.read_csv("../dags/data/raw/df_OrderItems.csv")
print(order_items.head())
# order_items.loc[:, ["product_id", "price"]].groupby("product_id").sum().plot(kind="barh")

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [6]:
orders = pd.read_csv("../dags/data/raw/df_Orders.csv", parse_dates=True)
print(orders.head())
orders.info()

       order_id   customer_id order_status order_purchase_timestamp  \
0  Axfy13Hk4PIk  hCT0x9JiGXBQ    delivered      2017-10-22 18:57:54
1  v6px92oS8cLG  PxA7fv9spyhx    delivered      2018-06-20 21:40:31
2  Ulpf9skrhjfm  g3nXeJkGI0Qw    delivered      2018-02-16 16:19:31
3  bwJVWupf2keN  EOEsCQ6QlpIg    delivered      2018-08-18 18:04:29
4  Dd0QnrMk9Cj5  mVz5LO2Vd6cL    delivered      2017-12-22 16:44:04

     order_approved_at order_delivered_timestamp order_estimated_delivery_date
0  2017-10-22 19:14:13       2017-10-26 22:19:52                    2017-11-09
1  2018-06-20 22:20:20       2018-07-03 22:51:22                    2018-07-24
2  2018-02-17 16:15:35       2018-02-27 01:29:50                    2018-03-08
3  2018-08-18 18:15:16       2018-08-27 20:03:51                    2018-09-19
4  2017-12-22 17:31:31       2018-01-05 19:22:49                    2018-01-18
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  object
 4   order_approved_at              89307 non-null  object
 5   order_delivered_timestamp      87427 non-null  object
 6   order_estimated_delivery_date  89316 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

In [15]:
import numpy as np
payments = pd.read_csv("../dags/data/raw/df_Payments.csv")
print(np.sum(payments["order_id"].value_counts() == 1), payments.shape)
payments.head(n=20)

89316 (89316, 5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15
5,VjTVGzqe8U6R,1,credit_card,4,1014.75
6,xNba906m4TM1,1,credit_card,1,123.79
7,VEDSMTavbQwk,1,credit_card,5,146.51
8,DzNM8wrcMGFH,1,wallet,1,1521.75
9,NpJz7zF9U1ae,1,credit_card,6,87.30
10,mHyhzcUeLGj2,1,credit_card,2,947.72
11,StM5K4TLyrt5,1,credit_card,1,60.56
12,Q97dFuo1kaq9,1,credit_card,10,110.32
13,07j6mlMhSVtx,1,credit_card,3,818.35
14,kxa1InBj9gwP,1,credit_card,1,254.94
15,P5R6jr1qZdh4,1,credit_card,10,98.42
16,HqV5f8K2UYoA,1,credit_card,3,281.52
17,j5rwgECNf14O,1,credit_card,2,182.83
18,43It0OEHVyJe,1,credit_card,1,38.35
19,ddXx4T93MeaI,1,credit_card,2,107.01

In [26]:
products = pd.read_csv("../dags/data/raw/df_Products.csv")
products.head()

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0